version: '3.3'
services:
  server:
    container_name: grpc-server-go
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "5001:5001"
      - "5000:5000"
    stdin_open: true  # -i
    tty: true         # -t
    links:
      - mongo
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer
  mongo:
    image: mongo:4.4.14
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/db/data
    environment:
      - GET_HOSTS_FROM=dns
  # TODO trial & error envoy proxy in this docker
  envoy:
    container_name: envoy-proxy
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
