apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server-tcp
  name: server-tcp
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: server
  type: LoadBalancer
status:
  loadBalancer: {}
